<table border="0" cellpadding="3" cellspacing="3">
<tr valign="top"><td>
<!-- BEGIN MAINIMAGE -->
{MAINIMAGE}
<!-- END MAINIMAGE -->
<!-- BEGIN MAINIMAGE_CAPTION -->
<br /><div align="center">{MAINIMAGE_CAPTION}</div><br /><br />
<!-- END MAINIMAGE_CAPTION -->
<!-- BEGIN THUMBIMAGE0 -->
{THUMBIMAGE0}<br /><br />
<!-- END THUMBIMAGE0 -->
<!-- BEGIN THUMBIMAGE2 -->
{THUMBIMAGE2}<br /><br />
<!-- END THUMBIMAGE2 -->
<!-- BEGIN THUMBIMAGE3 -->
{THUMBIMAGE3}<br /><br />
<!-- END THUMBIMAGE3 -->
<!-- BEGIN THUMBIMAGE4 -->
{THUMBIMAGE4}<br /><br />
<!-- END THUMBIMAGE4 -->
</td><td>
<!-- BEGIN TITLE -->
<h2>{TITLE}</h2>
<!-- END TITLE -->
<!-- BEGIN PRICE -->
<b>{PRICE_LABEL}</b>: {PRICE_SIGN} {PRICE}<br />
<!-- END PRICE -->
<!-- BEGIN MORTCALC -->
{MORTCALC}<br />
<!-- END MORTCALC -->
<!-- BEGIN FORMELEMENT0_LABEL -->
<b>{FORMELEMENT0_LABEL}</b>: 
<!-- END FORMELEMENT0_LABEL -->
<!-- BEGIN FORMELEMENT0 -->
{FORMELEMENT0}<br />
<!-- END FORMELEMENT0 -->
<!-- BEGIN FORMELEMENT1_LABEL -->
<b>{FORMELEMENT1_LABEL}</b>: 
<!-- END FORMELEMENT1_LABEL -->
<!-- BEGIN FORMELEMENT1 -->
{FORMELEMENT1}<br />
<!-- END FORMELEMENT1 -->
<!-- BEGIN FORMELEMENT2_LABEL -->
<b>{FORMELEMENT2_LABEL}</b>: 
<!-- END FORMELEMENT2_LABEL -->
<!-- BEGIN FORMELEMENT2 -->
{FORMELEMENT2}<br />
<!-- END FORMELEMENT2 -->
<!-- BEGIN FORMELEMENT3_LABEL -->
<b>{FORMELEMENT3_LABEL}</b>: 
<!-- END FORMELEMENT3_LABEL -->
<!-- BEGIN FORMELEMENT3 -->
{FORMELEMENT3}<br />
<!-- END FORMELEMENT3 -->
<!-- BEGIN FORMELEMENT4_LABEL -->
<b>{FORMELEMENT4_LABEL}</b>: 
<!-- END FORMELEMENT4_LABEL -->
<!-- BEGIN FORMELEMENT4 -->
{FORMELEMENT4}<br />
<!-- END FORMELEMENT4 -->
<!-- BEGIN NOTES -->
<b>{NOTES_LABEL}:</b><br />{NOTES}<br /><br />
<!-- END NOTES -->
<!-- BEGIN AGENTLINK -->
{AGENT_LABEL}: {AGENTLINK}<br />
<!-- END AGENTLINK -->
<!-- BEGIN AGENCYLINK -->
{AGENCY_LABEL}: {AGENCYLINK}<br />
<!-- END AGENCYLINK -->
<!-- BEGIN LISTEDON -->
{LISTEDON_LABEL}: {CREATIONDATE}<br />
<!-- END LISTEDON -->
<!-- BEGIN UPDATED -->
{UPDATEDON_LABEL}: {LASTMODIFIED}<br />
<!-- END UPDATED -->
<!-- BEGIN EXPIRATION -->
{EXPIRATION_LABEL}: {EXPIRATION}<br />
<!-- END EXPIRATION -->
<!-- BEGIN FEATURE -->
{FEATURE}<br />
<!-- END FEATURE -->
<!-- BEGIN SOLD -->
{SOLD}<br />
<!-- END SOLD -->
<!-- BEGIN HITS -->
Viewed: {HITS}<br /><br />
<!-- END HITS -->
<!-- BEGIN LINKS -->
{PRINTABLE}<br />
{EMAIL_FRIEND}<br />
{EMAIL_AGENT}
<!-- END LINKS -->
<!-- BEGIN EDITLINK -->
<br /><br /><b>[&nbsp;{EDITLINK}&nbsp;]</b>
<!-- END EDITLINK -->

</td></tr>
</table>