<table border="0" cellpadding="5" cellspacing="0">
<tr valign="top">
<td>
<!-- BEGIN AGENTID -->
{AGENTID_LABEL}: {AGENTID}<br />
<!-- END AGENTID -->
<!-- BEGIN AGENCY -->
{AGENCY_LABEL}: {AGENCY}<br />
<!-- END AGENCY -->
<!-- BEGIN TITLE -->
{TITLE_LABEL}: {TITLE}<br />
<!-- END TITLE -->
<!-- BEGIN PRICE -->
{MIN_PRICE_LABEL}: {PRICE_SIGN} {MIN_PRICE}<br />
{MAX_PRICE_LABEL}: {PRICE_SIGN} {MAX_PRICE}<br />
<!-- END PRICE -->
<!-- BEGIN FORMELEMENT_REQUIRED0 -->
<font color="red"><b>{FORMELEMENT_REQUIRED0}</b></font>
<!-- END FORMELEMENT_REQUIRED0 -->
<!-- BEGIN FORMELEMENT0_LABEL -->
{FORMELEMENT0_LABEL}
<!-- END FORMELEMENT0_LABEL -->
<!-- BEGIN FORMELEMENT0 -->
{FORMELEMENT0}<br />
<!-- END FORMELEMENT0 -->
<!-- BEGIN FORMELEMENT_REQUIRED1 -->
<font color="red"><b>{FORMELEMENT_REQUIRED1}</b></font>
<!-- END FORMELEMENT_REQUIRED1 -->
<!-- BEGIN FORMELEMENT1_LABEL -->
{FORMELEMENT1_LABEL}
<!-- END FORMELEMENT1_LABEL -->
<!-- BEGIN FORMELEMENT1 -->
{FORMELEMENT1}<br />
<!-- END FORMELEMENT1 -->
<!-- BEGIN FORMELEMENT_REQUIRED2 -->
<font color="red"><b>{FORMELEMENT_REQUIRED2}</b></font>
<!-- END FORMELEMENT_REQUIRED2 -->
<!-- BEGIN FORMELEMENT2_LABEL -->
{FORMELEMENT2_LABEL}
<!-- END FORMELEMENT2_LABEL -->
<!-- BEGIN FORMELEMENT2 -->
{FORMELEMENT2}<br />
<!-- END FORMELEMENT2 -->
<!-- BEGIN FORMELEMENT_REQUIRED3 -->
<font color="red"><b>{FORMELEMENT_REQUIRED3}</b></font>
<!-- END FORMELEMENT_REQUIRED3 -->
<!-- BEGIN FORMELEMENT3_LABEL -->
{FORMELEMENT3_LABEL}
<!-- END FORMELEMENT3_LABEL -->
<!-- BEGIN FORMELEMENT3 -->
{FORMELEMENT3}<br />
<!-- END FORMELEMENT3 -->
<!-- BEGIN FORMELEMENT_REQUIRED4 -->
<font color="red"><b>{FORMELEMENT_REQUIRED4}</b></font>
<!-- END FORMELEMENT_REQUIRED4 -->
<!-- BEGIN FORMELEMENT4_LABEL -->
{FORMELEMENT4_LABEL}
<!-- END FORMELEMENT4_LABEL -->
<!-- BEGIN FORMELEMENT4 -->
{FORMELEMENT4}<br />
<!-- END FORMELEMENT4 -->
<!-- BEGIN SORT -->
{SORT_LABEL}: {SORT_BY} {SORT_ORDER}<br />
<!-- END SORTBY -->
<!-- BEGIN SUBMIT -->
<br />{SUBMIT_BUTTON}
<!-- END SUBMIT -->
</td>
</tr>
</table>
