<!-- BEGIN CLASS -->
{CLASS_LABEL}: {CLASS}<br />
<!-- END CLASS -->
<!-- BEGIN FIELD_TYPE -->
{FIELD_TYPE_LABEL}: {FIELD_TYPE}&#160;{FIELD_TYPE_HELP}<br />
<!-- END FIELD_TYPE -->
<!-- BEGIN FIELD_NAME -->
{FIELD_NAME_LABEL}: {FIELD_NAME}&#160;{FIELD_NAME_HELP}<br />
<!-- END FIELD_NAME -->
<!-- BEGIN FIELD_CAPTION -->
{FIELD_CAPTION_LABEL}: {FIELD_CAPTION}&#160;{FIELD_CAPTION_HELP}<br />
<!-- END FIELD_CAPTION -->
<!-- BEGIN DEFAULT_TEXT -->
{DEFAULT_TEXT_LABEL}: {DEFAULT_TEXT}&#160;{DEFAULT_TEXT_HELP}<br />
<!-- END DEFAULT_TEXT -->
<!-- BEGIN FIELD_ELEMENTS -->
{FIELD_ELEMENTS_LABEL}: {FIELD_ELEMENTS}&#160;{FIELD_ELEMENTS_HELP}<br />
<font size="-2">{FIELD_ELEMENTS_SEPWARN}</font><br />
<!-- END FIELD_ELEMENTS -->
<!-- BEGIN RANK -->
{RANK_LABEL}: {RANK}&#160;{RANK_HELP}<br />
<!-- END RANK -->
<!-- BEGIN REQUIRED -->
{REQUIRED_LABEL}: {REQUIRED}&#160;{REQUIRED_HELP}<br />
<!-- END REQUIRED -->
<!-- BEGIN DISPLAY_ON_BROWSE -->
{DISPLAY_ON_BROWSE_LABEL}: {DISPLAY_ON_BROWSE}&#160;{DISPLAY_ON_BROWSE_HELP}<br />
<!-- END DISPLAY_ON_BROWSE -->
<!-- BEGIN AGENTONLY -->
{AGENTONLY_LABEL}: {AGENTONLY}&#160;{AGENTONLY_HELP}<br />
<!-- END AGENTONLY -->
<!-- BEGIN SUBMIT -->
<br />{SUBMIT_BUTTON}
<!-- END SUBMIT -->
