<!-- BEGIN SENDER -->
{SENDER_NAME_LABEL}: {SENDER_NAME}<br />
{SENDER_EMAIL_LABEL}: {SENDER_EMAIL}<br />
<!-- END SENDER -->
<!-- BEGIN RECIPIENT -->
{RECIPIENT_NAME_LABEL}: {RECIPIENT_NAME}<br />
{RECIPIENT_EMAIL_LABEL}: {RECIPIENT_EMAIL}<br />
<!-- END RECIPIENT -->
<!-- BEGIN COMMENTS -->
<br />{COMMENTS_LABEL}:<br />{COMMENTS}<br />
<!-- END COMMENTS -->
<!-- BEGIN SUBMIT -->
<br />{SUBMIT_BUTTON}
<!-- END SUBMIT -->
