{PAGINATE_LIMIT}{PAGINATE_LIMIT_LABEL}<br />
{LISTING_IMAGE_LIMIT}{LISTING_IMAGE_LIMIT_LABEL}<br />
<hr size="1" noshade />
{USE_EXPIRATION}<br />
{SHOW_MENU}<br />
{SHOW_FEATURE}<br />
{FEATURE_TITLE_LABEL}: {FEATURE_TITLE}<br />
{SHOW_BLOCK}<br />
{BLOCK_TITLE_LABEL}: {BLOCK_TITLE}<br />
{NUM_BLOCK}{NUM_BLOCK_LABEL}<br />
{BLOCK_IMAGES_ONLY}<br />
<hr size="1" noshade />
{IMAGESIZE_LIMIT}{IMAGESIZE_LIMIT_LABEL}<br />
{IMAGE_MAX_WIDTH}{IMAGE_MAX_WIDTH_LABEL}<br />
{IMAGE_MAX_HEIGHT}{IMAGE_MAX_HEIGHT_LABEL}<br />
{IMAGE_WIDTH_REDIM}{IMAGE_WIDTH_REDIM_LABEL}<br />
{IMAGE_HEIGHT_REDIM}{IMAGE_HEIGHT_REDIM_LABEL}<br />
<hr size="1" noshade />
<h4>{CUSTOM_SETTINGS_LABEL}</h4>
{USE_CUSTOM_LAYOUT}{ADVANCED_LAYOUT_HELP}<br /><br />
{SUBMIT}
