<!-- BEGIN FIELD_TYPE -->
{FIELD_TYPE_LABEL}: {FIELD_TYPE}<br />
<!-- END FIELD_TYPE -->
<!-- BEGIN FIELD_NAME -->
{FIELD_NAME_LABEL}: {FIELD_NAME}<br />
<!-- END FIELD_NAME -->
<!-- BEGIN FIELD_CAPTION -->
{FIELD_CAPTION_LABEL}: {FIELD_CAPTION}<br />
<!-- END FIELD_CAPTION -->
<!-- BEGIN DEFAULT_TEXT -->
{DEFAULT_TEXT_LABEL}: {DEFAULT_TEXT}<br />
<!-- END DEFAULT_TEXT -->
<!-- BEGIN FIELD_ELEMENTS -->
{FIELD_ELEMENTS_LABEL}: {FIELD_ELEMENTS}<br />
<font size="-2">{FIELD_ELEMENTS_SEPWARN}</font><br />
<!-- END FIELD_ELEMENTS -->
<!-- BEGIN RANK -->
{RANK_LABEL}: {RANK}<br />
<!-- END RANK -->
<!-- BEGIN REQUIRED -->
{REQUIRED_LABEL}: {REQUIRED}<br />
<!-- END REQUIRED -->
<!-- BEGIN DISPLAY_ON_BROWSE -->
{DISPLAY_ON_BROWSE_LABEL}: {DISPLAY_ON_BROWSE}<br />
<!-- END DISPLAY_ON_BROWSE -->
<!-- BEGIN AGENTONLY -->
{AGENTONLY_LABEL}: {AGENTONLY}<br />
<!-- END AGENTONLY -->
<!-- BEGIN SUBMIT -->
<br />{SUBMIT_BUTTON}
<!-- END SUBMIT -->
