{START_FORM}
{SETTINGS_ALLOW_ANON_VIEW} {ANONVIEW_TEXT}<br />
{SETTINGS_SORTBYFIRSTNAME} {SORTBY_TEXT}<br />
<br />
<b>{CUSTOMFIELDS_LABEL}</b>&#160;{CUSTOMFIELDS_HELP}<br />
{CUSTOM1LABEL_TEXT}: {SETTINGS_CUSTOM1LABEL}<br />
{CUSTOM2LABEL_TEXT}: {SETTINGS_CUSTOM2LABEL}<br />
{CUSTOM3LABEL_TEXT}: {SETTINGS_CUSTOM3LABEL}<br />
{CUSTOM4LABEL_TEXT}: {SETTINGS_CUSTOM4LABEL}<br />
{SETTINGS_SAVE}
{END_FORM}
