{START_FORM}
<h3>{MONITORS_TITLE}</h3>
<!-- BEGIN SETTINGS_MONITORDEFAULT -->
<label>{SETTINGS_MONITORDEFAULT} {MONITORDEFAULT_TEXT}</label><br />
<!-- END SETTINGS_MONITORDEFAULT -->
<!-- BEGIN MONITORDEFAULT_WARNING -->
<i>({MONITORDEFAULT_WARNING})</i><br />
<!-- END MONITORDEFAULT_WARNING -->
<!-- BEGIN SETTINGS_SUSPENDMONITORS -->
<label>{SETTINGS_SUSPENDMONITORS} {SUSPENDMONITORS_TEXT}</label>&#160;{SUSPENDMONITORS_HELP}<br />
<!-- END SETTINGS_SUSPENDMONITORS -->
<!-- BEGIN REMOVEALLMONITORS -->
{REMOVEALLMONITORS}&#160;{REMOVEALLMONITORS_HELP}<br />
<!-- END REMOVEALLMONITORS -->
<!-- BEGIN SETTINGS_LOCATION -->
<br />
<label>
<h3>{PERSONAL_TITLE}</h3>
<b>{LOCATION_LABEL}</b><br />
{SETTINGS_LOCATION}<br />
</label>
<!-- END SETTINGS_LOCATION -->
<!-- BEGIN SETTINGS_SIGNATURE -->
<br />
<label>
<b>{SIGNATURE_LABEL}</b><br />
{SIGNATURE_HELP}<br />
{SETTINGS_SIGNATURE}<br />
</label>
<!-- END SETTINGS_SIGNATURE -->
<br />
<!-- BEGIN AVC -->
<h3>{AVATAR_TITLE}</h3>
<!-- BEGIN CURRENT -->
<b>{CURRENT_AVATAR_LABEL}</b><br />
{CURRENT_AVATAR_IMG}<br />
{CURRENT_AVATAR_TEXT}<br />
<label>{REMOVE_AVATAR_LABEL} {SETTINGS_DELETE_IMAGE}</label><br />
<br />
<!-- END CURRENT -->
<label>
<b>{SELECT_AVATAR_LABEL}</b><br />
{SELECT_AVATAR_HELP}<br />
{IMGLIB_OP}<br />
</label>
<!-- BEGIN IMAGE_MGMT_TITLE -->
<br />
<b>{IMAGE_MGMT_TITLE}</b>
<!-- END IMAGE_MGMT_TITLE -->
<!-- BEGIN SETTINGS_AVATAR_FILE -->
<label>
<b>{REMOTE_AVATAR_LABEL}</b><br />
{REMOTE_AVATAR_HELP}<br />
{SETTINGS_AVATAR_FILE}<br />
</label>
<!-- END SETTINGS_AVATAR_FILE -->
<!-- END AVC -->
<br />
{SETTINGS_SAVE}
{END_FORM}
